export const SEND_LOCAL_MESSAGE = 'SEND_LOCAL_MESSAGE';
export const SEND_GLOBAL_MESSAGE = 'SEND_GLOBAL_MESSAGE';
export const SEND_BROADCAST_MESSAGE = 'SEND_BROADCAST_MESSAGE';
export const UPDATE_LOCAL_MESSAGE = 'UPDATE_LOCAL_MESSAGE';
export const UPDATE_GLOBAL_MESSAGE = 'UPDATE_GLOBAL_MESSAGE';
export const UPDATE_BROADCAST_MESSAGE = 'UPDATE_BROADCAST_MESSAGE';